FCLIB : a collection  of discrete 3D Frictional Contact (FC) problems
FCLIB
a collection of discrete 3D Frictional Contact (FC) problems
Home | Download | Publications | Contact us
fclib.c File Reference
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <hdf5.h>
#include <hdf5_hl.h>
#include "fclib.h"
#include "fcint.h"
Macros
#define H5Gcreate_vers 2
#define H5Gopen_vers 2
Functions
static hid_t H5Gmake (hid_t loc_id, const char *name)
make grourp
static void write_matrix (hid_t id, struct fclib_matrix *mat)
write matrix
struct fclib_matrix * read_matrix (hid_t id)
read matrix
static void write_global_vectors (hid_t id, struct fclib_global *problem)
write global vectors
static void read_global_vectors (hid_t id, struct fclib_global *problem)
read global vectors
static void write_local_vectors (hid_t id, struct fclib_local *problem)
write local vectors
static void read_local_vectors (hid_t id, struct fclib_local *problem)
read local vectors
static void write_problem_info (hid_t id, struct fclib_info *info)
write problem info
static struct fclib_info * read_problem_info (hid_t id)
read problem info
static void write_solution (hid_t id, struct fclib_solution *solution, hsize_t nv, hsize_t nr, hsize_t nl)
write solution
static void read_solution (hid_t id, hsize_t nv, hsize_t nr, hsize_t nl, struct fclib_solution *solution)
read solution
static int read_nvnunrnl (hid_t file_id, int *nv, int *nr, int *nl)
read solution sizes
static void delete_matrix_info (struct fclib_matrix_info *info)
delete matrix info
static void delete_matrix (struct fclib_matrix *mat)
delete matrix
static void delete_info (struct fclib_info *info)
delete problem info
int fclib_create_int_attributes_in_info (const char *path, const char *attr_name, int attr_value)
create and set attributes of tyoe int in info
int fclib_write_global (struct fclib_global *problem, const char *path)
write global problem; return 1 on success, 0 on failure
int fclib_write_local (struct fclib_local *problem, const char *path)
write local problem; return 1 on success, 0 on failure
int fclib_write_solution (struct fclib_solution *solution, const char *path)
write solution; return 1 on success, 0 on failure
int fclib_write_guesses (int number_of_guesses, struct fclib_solution *guesses, const char *path)
write initial guesses; return 1 on success, 0 on failure
struct fclib_global * fclib_read_global (const char *path)
read global problem; return problem on success; NULL on failure
struct fclib_local * fclib_read_local (const char *path)
read local problem; return problem on success; NULL on failure
struct fclib_solution * fclib_read_solution (const char *path)
read solution; return solution on success; NULL on failure
struct fclib_solution * fclib_read_guesses (const char *path, int *number_of_guesses)
read initial guesses; return vector of guesses on success; NULL on failure; output numebr of guesses in the variable pointed by 'number_of_guesses'
void fclib_delete_global (struct fclib_global *problem)
delete global problem
void fclib_delete_local (struct fclib_local *problem)
delete local problem
void fclib_delete_solutions (struct fclib_solution *data, int count)
delete solutions or guesses
Detailed Description
frictional contact library input/output
Definition in file fclib.c.
Macro Definition Documentation
#define H5Gcreate_vers 2
Definition at line 24 of file fclib.c.
#define H5Gopen_vers 2
Definition at line 25 of file fclib.c.
Function Documentation
static hid_t H5Gmake (hid_t loc_id, const char * name) static
make grourp
Definition at line 37 of file fclib.c.
Referenced by fclib_create_int_attributes_in_info(), fclib_write_global(), fclib_write_guesses(), fclib_write_local(), and fclib_write_solution().
static void write_matrix (hid_t id, struct fclib_matrix * mat) static
write matrix
Definition at line 51 of file fclib.c.
References ASSERT, fclib_matrix_info::comment, fclib_matrix_info::conditioning, fclib_matrix_info::determinant, fclib_matrix::i, fclib_matrix::info, IO, fclib_matrix::m, fclib_matrix::n, fclib_matrix::nz, fclib_matrix::nzmax, fclib_matrix::p, fclib_matrix_info::rank, and fclib_matrix::x.
Referenced by fclib_write_global(), and fclib_write_local().
struct fclib_matrix* read_matrix (hid_t id)
read matrix
Definition at line 96 of file fclib.c.
References ASSERT, fclib_matrix_info::comment, fclib_matrix_info::conditioning, fclib_matrix_info::determinant, fclib_matrix::i, fclib_matrix::info, IO, fclib_matrix::m, MM, fclib_matrix::n, fclib_matrix::nz, fclib_matrix::nzmax, fclib_matrix::p, fclib_matrix_info::rank, and fclib_matrix::x.
Referenced by fclib_read_global(), and fclib_read_local().
static void write_global_vectors (hid_t id, struct fclib_global * problem) static
write global vectors
Definition at line 156 of file fclib.c.
References ASSERT, fclib_global::b, fclib_global::f, fclib_global::G, fclib_global::H, IO, fclib_matrix::m, fclib_global::M, fclib_global::mu, fclib_matrix::n, fclib_global::spacedim, and fclib_global::w.
Referenced by fclib_write_global().
static void read_global_vectors (hid_t id, struct fclib_global * problem) static
read global vectors
Definition at line 180 of file fclib.c.
References ASSERT, fclib_global::b, fclib_global::f, fclib_global::G, fclib_global::H, IO, fclib_matrix::m, fclib_global::M, MM, fclib_global::mu, fclib_matrix::n, fclib_global::spacedim, and fclib_global::w.
Referenced by fclib_read_global().
static void write_local_vectors (hid_t id, struct fclib_local * problem) static
write local vectors
Definition at line 199 of file fclib.c.
References ASSERT, IO, fclib_matrix::m, fclib_local::mu, fclib_local::q, fclib_local::R, fclib_local::s, fclib_local::spacedim, fclib_local::V, and fclib_local::W.
Referenced by fclib_write_local().
static void read_local_vectors (hid_t id, struct fclib_local * problem) static
read local vectors
Definition at line 220 of file fclib.c.
References ASSERT, IO, fclib_matrix::m, MM, fclib_local::mu, fclib_local::q, fclib_local::R, fclib_local::s, fclib_local::spacedim, and fclib_local::W.
Referenced by fclib_read_local().
static void write_problem_info (hid_t id, struct fclib_info * info) static
write problem info
Definition at line 237 of file fclib.c.
References fclib_info::description, IO, fclib_info::math_info, and fclib_info::title.
Referenced by fclib_write_global(), and fclib_write_local().
static struct fclib_info* read_problem_info (hid_t id) static
read problem info
Definition at line 245 of file fclib.c.
References fclib_info::description, IO, fclib_info::math_info, MM, and fclib_info::title.
Referenced by fclib_read_global(), and fclib_read_local().
static void write_solution (hid_t id, struct fclib_solution * solution, hsize_t nv, hsize_t nr, hsize_t nl) static
write solution
Definition at line 282 of file fclib.c.
References ASSERT, IO, fclib_solution::l, fclib_solution::r, fclib_solution::u, and fclib_solution::v.
Referenced by fclib_write_guesses(), and fclib_write_solution().
static void read_solution (hid_t id, hsize_t nv, hsize_t nr, hsize_t nl, struct fclib_solution * solution) static
read solution
Definition at line 293 of file fclib.c.
References ASSERT, IO, fclib_solution::l, MM, fclib_solution::r, fclib_solution::u, and fclib_solution::v.
Referenced by fclib_read_guesses(), and fclib_read_solution().
static int read_nvnunrnl (hid_t file_id, int * nv, int * nr, int * nl) static
read solution sizes
Definition at line 317 of file fclib.c.
References IO.
Referenced by fclib_read_guesses(), fclib_read_solution(), fclib_write_guesses(), and fclib_write_solution().
static void delete_matrix_info (struct fclib_matrix_info * info) static
delete matrix info
Definition at line 349 of file fclib.c.
References fclib_matrix_info::comment.
Referenced by delete_matrix().
static void delete_matrix (struct fclib_matrix * mat) static
delete matrix
Definition at line 359 of file fclib.c.
References delete_matrix_info(), fclib_matrix::i, fclib_matrix::info, fclib_matrix::p, and fclib_matrix::x.
Referenced by fclib_delete_global(), and fclib_delete_local().
static void delete_info (struct fclib_info * info) static
delete problem info
Definition at line 372 of file fclib.c.
References fclib_info::description, fclib_info::math_info, and fclib_info::title.
Referenced by fclib_delete_global(), and fclib_delete_local().
int fclib_create_int_attributes_in_info (const char * path, const char * attr_name, int attr_value)
create and set attributes of tyoe int in info
Definition at line 382 of file fclib.c.
References H5Gmake(), and IO.
int fclib_write_global (struct fclib_global * problem, const char * path)
write global problem; return 1 on success, 0 on failure
Definition at line 431 of file fclib.c.
References ASSERT, fclib_global::G, fclib_global::H, H5Gmake(), fclib_global::info, IO, fclib_global::M, fclib_global::spacedim, write_global_vectors(), write_matrix(), and write_problem_info().
Referenced by main().
int fclib_write_local (struct fclib_local * problem, const char * path)
write local problem; return 1 on success, 0 on failure
Definition at line 503 of file fclib.c.
References ASSERT, H5Gmake(), fclib_local::info, IO, fclib_local::R, fclib_local::spacedim, fclib_local::V, fclib_local::W, write_local_vectors(), write_matrix(), and write_problem_info().
Referenced by main().
int fclib_write_solution (struct fclib_solution * solution, const char * path)
write solution; return 1 on success, 0 on failure
Definition at line 571 of file fclib.c.
References H5Gmake(), IO, read_nvnunrnl(), and write_solution().
Referenced by main().
int fclib_write_guesses (int number_of_guesses, struct fclib_solution * guesses, const char * path)
write initial guesses; return 1 on success, 0 on failure
Definition at line 611 of file fclib.c.
References H5Gmake(), IO, read_nvnunrnl(), and write_solution().
Referenced by main().
struct fclib_global* fclib_read_global (const char * path)
read global problem; return problem on success; NULL on failure
Definition at line 661 of file fclib.c.
References fclib_global::G, fclib_global::H, fclib_global::info, IO, fclib_global::M, MM, read_global_vectors(), read_matrix(), read_problem_info(), and fclib_global::spacedim.
Referenced by main().
struct fclib_local* fclib_read_local (const char * path)
read local problem; return problem on success; NULL on failure
Definition at line 711 of file fclib.c.
References fclib_local::info, IO, MM, fclib_local::R, read_local_vectors(), read_matrix(), read_problem_info(), fclib_local::spacedim, fclib_local::V, and fclib_local::W.
Referenced by main().
struct fclib_solution* fclib_read_solution (const char * path)
read solution; return solution on success; NULL on failure
Definition at line 761 of file fclib.c.
References IO, MM, read_nvnunrnl(), and read_solution().
Referenced by main().
struct fclib_solution* fclib_read_guesses (const char * path, int * number_of_guesses)
read initial guesses; return vector of guesses on success; NULL on failure; output numebr of guesses in the variable pointed by 'number_of_guesses'
Definition at line 789 of file fclib.c.
References IO, MM, read_nvnunrnl(), and read_solution().
Referenced by main().
void fclib_delete_global (struct fclib_global * problem)
delete global problem
Definition at line 829 of file fclib.c.
References fclib_global::b, delete_info(), delete_matrix(), fclib_global::f, fclib_global::G, fclib_global::H, fclib_global::info, fclib_global::M, fclib_global::mu, and fclib_global::w.
Referenced by main().
void fclib_delete_local (struct fclib_local * problem)
delete local problem
Definition at line 842 of file fclib.c.
References delete_info(), delete_matrix(), fclib_local::info, fclib_local::mu, fclib_local::q, fclib_local::R, fclib_local::s, fclib_local::V, and fclib_local::W.
Referenced by main().
void fclib_delete_solutions (struct fclib_solution * data, int count)
delete solutions or guesses
Definition at line 854 of file fclib.c.
References fclib_solution::l, fclib_solution::r, fclib_solution::u, and fclib_solution::v.
Referenced by main().