FCLIB : a collection  of discrete 3D Frictional Contact (FC) problems
FCLIB
a collection of discrete 3D Frictional Contact (FC) problems
Home | Download | Publications | Contact us
fcmer.c File Reference
#include <string.h>
#include <stdlib.h>
#include <hdf5.h>
#include <hdf5_hl.h>
#include "fclib.h"
#include "fcint.h"
#include "math.h"
Functions
static double dnrm2 (double *v, int n)
static void projectionOnCone (double *r, double mu)
void FrictionContact3D_unitary_compute_and_add_error (double *z, double *w, double mu, double *error)
double fclib_merit_global (struct fclib_global *problem, enum fclib_merit merit, struct fclib_solution *solution)
calculate merit function for a global problem
double fclib_merit_local (struct fclib_local *problem, enum fclib_merit merit, struct fclib_solution *solution)
calculate merit function for a local problem
Function Documentation
static double dnrm2 (double * v, int n) inline static
Definition at line 27 of file fcmer.c.
Referenced by fclib_merit_local().
static void projectionOnCone (double * r, double mu) inline static
Definition at line 35 of file fcmer.c.
Referenced by FrictionContact3D_unitary_compute_and_add_error().
void FrictionContact3D_unitary_compute_and_add_error (double * z, double * w, double mu, double * error)
Definition at line 59 of file fcmer.c.
References projectionOnCone().
Referenced by fclib_merit_local().
double fclib_merit_global (struct fclib_global * problem, enum fclib_merit merit, struct fclib_solution * solution)
calculate merit function for a global problem
Definition at line 78 of file fcmer.c.
Referenced by main().
double fclib_merit_local (struct fclib_local * problem, enum fclib_merit merit, struct fclib_solution * solution)
calculate merit function for a local problem
Definition at line 84 of file fcmer.c.
References dnrm2(), FrictionContact3D_unitary_compute_and_add_error(), fclib_matrix::i, fclib_solution::l, MERIT_1, fclib_local::mu, fclib_matrix::n, fclib_local::q, fclib_local::R, fclib_solution::r, fclib_local::s, fclib_local::spacedim, fclib_solution::u, fclib_local::V, fclib_solution::v, and fclib_local::W.
Referenced by main().