FCLIB : a collection  of discrete 3D Frictional Contact (FC) problems
FCLIB
a collection of discrete 3D Frictional Contact (FC) problems
Home | Download | Publications | Contact us
fctst.c File Reference
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include "fclib.h"
#include "fcint.h"
Functions
static struct fclib_matrix_info * matrix_info (struct fclib_matrix *mat, char *comment)
static struct fclib_matrix * random_matrix (int m, int n)
static double * random_vector (int n)
static struct fclib_info * problem_info (char *title, char *desc, char *math)
static struct fclib_global * random_global_problem (int global_dofs, int contact_points, int neq)
static struct fclib_solution * random_global_solutions (struct fclib_global *problem, int count)
static struct fclib_local * random_local_problem (int contact_points, int neq)
static struct fclib_solution * random_local_solutions (struct fclib_local *problem, int count)
static int compare_matrix_infos (struct fclib_matrix_info *a, struct fclib_matrix_info *b)
static int compare_matrices (char *name, struct fclib_matrix *a, struct fclib_matrix *b)
static int compare_vectors (char *name, int n, double *a, double *b)
static int compare_infos (struct fclib_info *a, struct fclib_info *b)
static int compare_global_problems (struct fclib_global *a, struct fclib_global *b)
static int compare_local_problems (struct fclib_local *a, struct fclib_local *b)
static int compare_solutions (struct fclib_solution *a, struct fclib_solution *b, int nv, int nr, int nl)
int main (int argc, char **argv)
Function Documentation
static struct fclib_matrix_info* matrix_info (struct fclib_matrix * mat, char * comment) static
Definition at line 33 of file fctst.c.
References fclib_matrix_info::comment, fclib_matrix_info::conditioning, fclib_matrix_info::determinant, fclib_matrix::m, MM, and fclib_matrix_info::rank.
Referenced by random_matrix().
static struct fclib_matrix* random_matrix (int m, int n) static
Definition at line 48 of file fctst.c.
References fclib_matrix::i, fclib_matrix::info, fclib_matrix::m, matrix_info(), MM, fclib_matrix::n, fclib_matrix::nz, fclib_matrix::nzmax, fclib_matrix::p, and fclib_matrix::x.
Referenced by random_global_problem(), and random_local_problem().
static double* random_vector (int n) static
Definition at line 91 of file fctst.c.
References MM.
Referenced by random_global_problem(), random_global_solutions(), random_local_problem(), and random_local_solutions().
static struct fclib_info* problem_info (char * title, char * desc, char * math) static
Definition at line 102 of file fctst.c.
References fclib_info::description, fclib_info::math_info, MM, and fclib_info::title.
Referenced by random_global_problem(), and random_local_problem().
static struct fclib_global* random_global_problem (int global_dofs, int contact_points, int neq) static
Definition at line 118 of file fctst.c.
References fclib_global::b, fclib_global::f, fclib_global::G, fclib_global::H, fclib_global::info, fclib_global::M, MM, fclib_global::mu, fclib_matrix::n, problem_info(), random_matrix(), random_vector(), fclib_global::spacedim, and fclib_global::w.
Referenced by main().
static struct fclib_solution* random_global_solutions (struct fclib_global * problem, int count) static
Definition at line 141 of file fctst.c.
References fclib_global::G, fclib_global::H, fclib_solution::l, fclib_global::M, MM, fclib_matrix::n, fclib_solution::r, random_vector(), fclib_solution::u, and fclib_solution::v.
Referenced by main().
static struct fclib_local* random_local_problem (int contact_points, int neq) static
Definition at line 161 of file fctst.c.
References fclib_local::info, MM, fclib_local::mu, problem_info(), fclib_local::q, fclib_local::R, random_matrix(), random_vector(), fclib_local::s, fclib_local::spacedim, fclib_local::V, and fclib_local::W.
Referenced by main().
static struct fclib_solution* random_local_solutions (struct fclib_local * problem, int count) static
Definition at line 189 of file fctst.c.
References fclib_solution::l, MM, fclib_matrix::n, fclib_local::R, fclib_solution::r, random_vector(), fclib_solution::u, fclib_solution::v, and fclib_local::W.
Referenced by main().
static int compare_matrix_infos (struct fclib_matrix_info * a, struct fclib_matrix_info * b) static
Definition at line 209 of file fctst.c.
References fclib_matrix_info::comment, fclib_matrix_info::conditioning, fclib_matrix_info::determinant, and fclib_matrix_info::rank.
Referenced by compare_matrices().
static int compare_matrices (char * name, struct fclib_matrix * a, struct fclib_matrix * b) static
Definition at line 222 of file fctst.c.
References compare_matrix_infos(), fclib_matrix::i, fclib_matrix::info, fclib_matrix::m, fclib_matrix::n, fclib_matrix::nz, fclib_matrix::nzmax, fclib_matrix::p, and fclib_matrix::x.
Referenced by compare_global_problems(), and compare_local_problems().
static int compare_vectors (char * name, int n, double * a, double * b) static
Definition at line 327 of file fctst.c.
Referenced by compare_global_problems(), compare_local_problems(), and compare_solutions().
static int compare_infos (struct fclib_info * a, struct fclib_info * b) static
Definition at line 347 of file fctst.c.
References fclib_info::description, fclib_info::math_info, and fclib_info::title.
Referenced by compare_global_problems(), and compare_local_problems().
static int compare_global_problems (struct fclib_global * a, struct fclib_global * b) static
Definition at line 359 of file fctst.c.
References fclib_global::b, compare_infos(), compare_matrices(), compare_vectors(), fclib_global::f, fclib_global::G, fclib_global::H, fclib_global::info, fclib_matrix::m, fclib_global::M, fclib_global::mu, fclib_matrix::n, fclib_global::spacedim, and fclib_global::w.
Referenced by main().
static int compare_local_problems (struct fclib_local * a, struct fclib_local * b) static
Definition at line 375 of file fctst.c.
References compare_infos(), compare_matrices(), compare_vectors(), fclib_local::info, fclib_local::mu, fclib_matrix::n, fclib_local::q, fclib_local::R, fclib_local::s, fclib_local::spacedim, fclib_local::V, and fclib_local::W.
Referenced by main().
static int compare_solutions (struct fclib_solution * a, struct fclib_solution * b, int nv, int nr, int nl) static
Definition at line 390 of file fctst.c.
References compare_vectors(), fclib_solution::l, fclib_solution::r, fclib_solution::u, and fclib_solution::v.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 400 of file fctst.c.
References ASSERT, compare_global_problems(), compare_local_problems(), compare_solutions(), fclib_delete_global(), fclib_delete_local(), fclib_delete_solutions(), fclib_merit_local(), fclib_read_global(), fclib_read_guesses(), fclib_read_local(), fclib_read_solution(), fclib_write_global(), fclib_write_guesses(), fclib_write_local(), fclib_write_solution(), fclib_global::G, fclib_global::H, fclib_matrix::m, fclib_global::M, MERIT_1, fclib_matrix::n, fclib_local::R, random_global_problem(), random_global_solutions(), random_local_problem(), random_local_solutions(), and fclib_local::W.